### ISSUE TITLE
受賞記事のリンク貼り忘れ＆リンク切れ探し

### ISSUE THREAD

**Issue by inox-ee** [sdm-wg/sdm-web#18]
## 概要

- #15 で付け忘れたリンクを追加する
- リンク先のページで リンク切れがあるかチェックする

**Comment by manabu525** [comment]
一応これで、何個か見つけて修正しました。
https://www.deadlinkchecker.com/website-dead-link-checker.asp

**Comment by inox-ee** [comment]
こんな便利なものあるんですね…ありがとうございます 🙇 
おそらく古い記事には index.ja.html や event.ja.html へのリンクも残っていると思うので、そちらもチェックしてみます
